### ISSUE TITLE
code review 

### ISSUE THREAD

**Issue by arunsai63** [arunsai63/algorithms#1]
https://github.com/arunsai63/algorithms/blob/c1c297dbf752be9e0193d2e9df39b9a8122c165c/dotnet-algo/DS/SinglyLinkedList.cs#L25

hey @ravi-n4s  can you review this

**Comment by ravi-n4s** [comment]
that's very nice and simple way of getting length in SLL...!!
but why private

**Comment by arunsai63** [comment]
Since we have to pass the head node initially and the head node is private, I have made the method as private and exposed the Length as a property 
(https://github.com/arunsai63/algorithms/blob/c1c297dbf752be9e0193d2e9df39b9a8122c165c/dotnet-algo/DS/SinglyLinkedList.cs#L23)
